---
title: "ggthemes"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(ggthemes)
library(dplyr)
```

```{r input}

selectInput("choice","Select Plot",c("Histogram","Line","Scatter"))

```


```{r plots}

p1 <- ggplot(iris, aes(Sepal.Length,fill="red",colour="grey")) + geom_histogram()

p2 <- ggplot(mtcars, aes(x = wt, y = mpg, colour = factor(gear))) +
  geom_point() +
  ggtitle("Cars")

p3 <- airquality %>% 
  mutate(date=as.Date(paste0("1973-",Month,"-",Day))) %>% 
  ggplot(aes(x= date,y=Temp))+ geom_line(colour="#ed448d")

```

Row
-----------------------------------------------------------------------

### Economist 

```{r economist}

output$economist <- renderPlot({

  
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_economist() + scale_colour_economist(), 
  "Scatter" = p2 + theme_economist() + scale_colour_economist(),
  "Line" = p3 + theme_economist() + scale_colour_economist()
  )
  p


})
plotOutput("economist")

```


### Solarized light

```{r solarized_l}

output$light <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_solarized() +   scale_colour_solarized("blue"),
  "Scatter" = p2 + theme_solarized() +   scale_colour_solarized("blue"),
  "Line" = p3 + theme_solarized() + scale_colour_solarized("blue")
  )
  p
  })
  plotOutput("light")
```

### Solarized dark

```{r solarized_d}

output$dark <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_solarized(light = FALSE) +   scale_colour_solarized("red"),
  "Scatter" = p2 + theme_solarized(light = FALSE) +   scale_colour_solarized("red"),
  "Line" = p3 + theme_solarized(light = FALSE) +   scale_colour_solarized("red")
  )
  p
  })
  plotOutput("dark")



```

### Stata

```{r stata}

output$stata <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_stata() + scale_colour_stata(),
  "Scatter" = p2 + theme_stata() + scale_colour_stata(),
  "Line" = p3 + theme_stata() + scale_colour_stata()
  )
  p
  })
  plotOutput("stata")


```

Row
-----------------------------------------------------------------------

### Inverse Gray

```{r inverse}

output$inverse <- renderPlot({

  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_igray(),
  "Scatter" = p2 + theme_igray(),
  "Line" = p3 + theme_igray()
  )
  p
  })


plotOutput("inverse")

```


### Fivethirtyeight

```{r Fivethirtyeight}

output$Fivethirtyeight <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_fivethirtyeight() +   scale_color_fivethirtyeight(),
  "Scatter" = p2 + theme_fivethirtyeight() +    scale_color_fivethirtyeight(),
  "Line" = p3 + theme_fivethirtyeight() +    scale_color_fivethirtyeight()
  )
  p
  })
  plotOutput("Fivethirtyeight")
```

### Paul Tol

```{r ptol}

output$ptol <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_minimal() +   scale_colour_ptol(),
  "Scatter" = p2 + theme_minimal() +   scale_colour_ptol(),
  "Line" = p3 + theme_minimal() +   scale_colour_ptol()
  )
  p
  })
  plotOutput("ptol")



```

### Tableau Scales

```{r tableau}

output$tableau <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_igray() + scale_colour_tableau(),
  "Scatter" = p2 + theme_igray() + scale_colour_tableau(),
  "Line" = p3 + theme_igray() + scale_colour_tableau()
  )
  p
  })
  plotOutput("tableau")


```

Row
-----------------------------------------------------------------------

### Wall Street Journal

```{r wsj}

output$wsj <- renderPlot({
 p <- switch(
  input$choice,
  "Histogram" = p1 + theme_wsj(), 
  "Scatter" = p2 + theme_wsj(),
  "Line" = p3 + theme_wsj() 
  )
  p
  })


plotOutput("wsj")

```


### Google Docs

```{r Google}

output$gdocs <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_gdocs() +   scale_color_gdocs(),
  "Scatter" = p2 + theme_gdocs() +    scale_color_gdocs(),
   "Line" = p3 + theme_gdocs() +    scale_color_gdocs()
  )
  p
  })
  plotOutput("gdocs")
```

### Highcharts Dark

```{r hc}

output$hc <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1 + theme_hc(bgcolor = "darkunica") +   scale_colour_hc("darkunica"),
  "Scatter" = p2 + theme_hc(bgcolor = "darkunica") +   scale_colour_hc("darkunica"),
  "Line" = p3 + theme_hc(bgcolor = "darkunica") +   scale_colour_hc("darkunica")
  )
  p
  })
  plotOutput("hc")



```

### out the Box

```{r ggplot2}

output$gg <- renderPlot({
  p <- switch(
  input$choice,
  "Histogram" = p1,
  "Scatter" = p2,
  "Line" = p3 
  )
  p
  })
  plotOutput("gg")


```